Homework lesson 4
Otus-DevOps-2018-11/palekseym_infra pull request #1
Opened 2018-12-25 16:12 UTC by palekseym

2018-12-26 14:48 UTC, palekseym commented
End lesson 4

2018-12-29 13:35 UTC, mrgreyves requested changes
Здравствуйте! Заполните пожалуйста пуллреквест. Спасибо!)

2019-01-07 08:56 UTC, palekseym commented
# Выполнено ДЗ № 4

 - [X] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Создана директория .github в которой размещен файл PULL_REQUEST_TEMPLATE.md
 - Настроена интеграция  github, slack и Travis CI
 - Исправлена ошибка юнит-теста в файле  test.py и проверен билд в travic ci

## Как запустить проект:
 - Запушить коммит в репозиторий на github

## Как проверить работоспособность:
 - В slack https://devops-team-otus.slack.com канала #alexey_puzikov придет уведомление об успешном билде.

## PR checklist
 - [X] Выставил label с темой домашнего задания

2019-01-07 09:25 UTC, mrgreyves approved these changes
Здравствуйте! Спасибо, дз принимаю!)

2019-01-07 11:40 UTC, merged